name: LOTM
version: '${project.version}'
main: de.firecreeper82.lotm.Plugin
api-version: 1.19
authors: [ FireCreeper82 ]
description: A Fan made Lord of the Mysteries plugin
commands:
  beyonder:
    description: make yourself a Beyonder
    usage: /<cmd>
  items:
    description: Give yourself the items from your pathway
    usage: /<cmd>
  disable-threads:
    description: choose the Spirit Body Threads you want to see
    usage: /<cmd>

