name: LOTM
version: '${project.version}'
main: de.firecreeper82.lotm.Plugin
api-version: 1.19
authors: [ FireCreeper82 ]
description: A Fan made Lord of the Mysteries plugin
commands:
  beyonder:
    description: For testing
    usage: /<cmd>
  items:
    description: give yourself the items from your pathway
    usage: /<cmd>
